Create an array of interferogram IDs. First column = SLC1, Second column = SLC2. Creating a network that only includes sequential, skip1, and skip2 interferograms. <br><br>

Written 6-7-23.
***

In [16]:
import os,sys
import glob
#import pandas as pd
import math
#import scipy
#from osgeo import gdal
import numpy as np
from array import array
#from scipy  import signal
import matplotlib.pyplot as plt
#import matplotlib.patches as mpatches
#from scipy.stats import gaussian_kde
import itertools
%matplotlib  widget

In [17]:
# load in dates
workdir = '/data/ocp4/LagunaSalada/Data_and_Figs/cropped_9000_1800_18000_3600/'
dates = [os.path.basename(x) for x in glob.glob(workdir+"SLC_vv/2*")]
dates = sorted(dates)
nd = len(dates); numIgrams = nd-1

In [18]:
# How many potential igram pairs are there in my 211 dates? Spanning all different lengths
#num_potential_igrams = scipy.special.comb(nd,2,exact=True)
num_potential_igrams = math.comb(nd,2)
print(str(num_potential_igrams)+' potential pairs.')

22155 potential pairs.


In [19]:
def nchoosek(startnum, endnum, step=1, n=2):
    num_potential_igrams = math.comb(endnum-startnum,2)+(endnum-startnum)
    c = np.zeros((num_potential_igrams,2))
    count = 0
    for i in itertools.combinations(range(startnum,endnum+1,step),n):
        c[count,0] = i[0]
        c[count,1] = i[1]
        count = count+1
    return c
intid = nchoosek(0, nd-1)
print(intid)

[[  0.   1.]
 [  0.   2.]
 [  0.   3.]
 ...
 [208. 209.]
 [208. 210.]
 [209. 210.]]


In [20]:
diffs = np.diff(intid,axis=1)
for i in range(np.shape(intid)[0]):
    print(intid[i],diffs[i])

[0. 1.] [1.]
[0. 2.] [2.]
[0. 3.] [3.]
[0. 4.] [4.]
[0. 5.] [5.]
[0. 6.] [6.]
[0. 7.] [7.]
[0. 8.] [8.]
[0. 9.] [9.]
[ 0. 10.] [10.]
[ 0. 11.] [11.]
[ 0. 12.] [12.]
[ 0. 13.] [13.]
[ 0. 14.] [14.]
[ 0. 15.] [15.]
[ 0. 16.] [16.]
[ 0. 17.] [17.]
[ 0. 18.] [18.]
[ 0. 19.] [19.]
[ 0. 20.] [20.]
[ 0. 21.] [21.]
[ 0. 22.] [22.]
[ 0. 23.] [23.]
[ 0. 24.] [24.]
[ 0. 25.] [25.]
[ 0. 26.] [26.]
[ 0. 27.] [27.]
[ 0. 28.] [28.]
[ 0. 29.] [29.]
[ 0. 30.] [30.]
[ 0. 31.] [31.]
[ 0. 32.] [32.]
[ 0. 33.] [33.]
[ 0. 34.] [34.]
[ 0. 35.] [35.]
[ 0. 36.] [36.]
[ 0. 37.] [37.]
[ 0. 38.] [38.]
[ 0. 39.] [39.]
[ 0. 40.] [40.]
[ 0. 41.] [41.]
[ 0. 42.] [42.]
[ 0. 43.] [43.]
[ 0. 44.] [44.]
[ 0. 45.] [45.]
[ 0. 46.] [46.]
[ 0. 47.] [47.]
[ 0. 48.] [48.]
[ 0. 49.] [49.]
[ 0. 50.] [50.]
[ 0. 51.] [51.]
[ 0. 52.] [52.]
[ 0. 53.] [53.]
[ 0. 54.] [54.]
[ 0. 55.] [55.]
[ 0. 56.] [56.]
[ 0. 57.] [57.]
[ 0. 58.] [58.]
[ 0. 59.] [59.]
[ 0. 60.] [60.]
[ 0. 61.] [61.]
[ 0. 62.] [62.]
[ 0. 63.] [63.]
[ 0. 64.] [64.]
[ 0

In [21]:
inds = np.where(diffs <= 3)
#print(np.shape(inds))
#print(inds[0])

In [22]:
intid2_a = intid[inds,0]
intid2_b = intid[inds,1]
intid2_a = intid2_a[0]
intid2_b = intid2_b[0]
intid2 = np.vstack((intid2_a,intid2_b))
intid2 = intid2.T
print(np.shape(intid2))
print(intid2)

(627, 2)
[[  0.   1.]
 [  0.   2.]
 [  0.   3.]
 ...
 [208. 209.]
 [208. 210.]
 [209. 210.]]


In [23]:
intid3 = np.ndarray((np.shape(intid2)),dtype='int')
for i in range(np.shape(intid2)[0]):
    intid3[i,0] = int(intid2[i,0])
    intid3[i,1] = int(intid2[i,1])
print(intid3)

[[  0   1]
 [  0   2]
 [  0   3]
 ...
 [208 209]
 [208 210]
 [209 210]]


In [24]:
for i in range(np.shape(intid2)[0]):
    print(intid3[i])

[0 1]
[0 2]
[0 3]
[1 2]
[1 3]
[1 4]
[2 3]
[2 4]
[2 5]
[3 4]
[3 5]
[3 6]
[4 5]
[4 6]
[4 7]
[5 6]
[5 7]
[5 8]
[6 7]
[6 8]
[6 9]
[7 8]
[7 9]
[ 7 10]
[8 9]
[ 8 10]
[ 8 11]
[ 9 10]
[ 9 11]
[ 9 12]
[10 11]
[10 12]
[10 13]
[11 12]
[11 13]
[11 14]
[12 13]
[12 14]
[12 15]
[13 14]
[13 15]
[13 16]
[14 15]
[14 16]
[14 17]
[15 16]
[15 17]
[15 18]
[16 17]
[16 18]
[16 19]
[17 18]
[17 19]
[17 20]
[18 19]
[18 20]
[18 21]
[19 20]
[19 21]
[19 22]
[20 21]
[20 22]
[20 23]
[21 22]
[21 23]
[21 24]
[22 23]
[22 24]
[22 25]
[23 24]
[23 25]
[23 26]
[24 25]
[24 26]
[24 27]
[25 26]
[25 27]
[25 28]
[26 27]
[26 28]
[26 29]
[27 28]
[27 29]
[27 30]
[28 29]
[28 30]
[28 31]
[29 30]
[29 31]
[29 32]
[30 31]
[30 32]
[30 33]
[31 32]
[31 33]
[31 34]
[32 33]
[32 34]
[32 35]
[33 34]
[33 35]
[33 36]
[34 35]
[34 36]
[34 37]
[35 36]
[35 37]
[35 38]
[36 37]
[36 38]
[36 39]
[37 38]
[37 39]
[37 40]
[38 39]
[38 40]
[38 41]
[39 40]
[39 41]
[39 42]
[40 41]
[40 42]
[40 43]
[41 42]
[41 43]
[41 44]
[42 43]
[42 44]
[42 45]
[43 44]
[43 45]


In [25]:
print(type(intid3[0,1]))

<class 'numpy.int64'>


Save to a text file.

In [26]:
# put it into a file 
file = open('/data/ocp4/LagunaSalada/Data_and_Figs/1_igrams/network_bw3.txt', 'w+')
for i in range(np.shape(intid3)[0]):
    file.write(str(intid3[i,0])+' '+str(intid3[i,1])+'\n')
file.close()